version: '2'
networks: 
    bridge-network: 
        driver: bridge

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    networks: 
      - bridge-network
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always

  kafka:
    container_name: kafka
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    networks: 
      - bridge-network
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: always

  producer:
    container_name: sensor
    build: sensors/
    networks: 
      - bridge-network
    restart: always

  consumer:
    container_name: consumer
    build: node
    networks: 
      - bridge-network
    restart: always

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
