apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-wmd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "hello-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1d
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: frontend
              servicePort: 80
          - path: /api/
            pathType: Prefix
            backend:
              serviceName: backend
              servicePort: 5001
          - path: /api/auth
            pathType: Prefix
            backend:
              serviceName: backend-auth
              servicePort: 4000
          - path: /socket.io
            pathType: Prefix
            backend:
              serviceName: backend
              servicePort: 5001