apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: docker.io/bitnami/kafka:2-debian-10
        env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zk-cs:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_CFG_LISTENERS
            #   value: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092"
            # - name: KAFKA_CFG_ADVERTISED_LISTENERS
            #   value: "PLAINTEXT://:9092,PLAINTEXT_HOST://kafka:29092"
            # - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
            #   value: "3"
        # resources:
        #   limits:
        #     memory: "1024Mi"
        #     cpu: "1500m"
        ports:
        - containerPort: 9092
  