apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 3
  selector:  # Specifies how deployment finds pods
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: vue-frontend
        image: ubervelocity/wmd-frontend
        ports:
        - containerPort: 80